### ISSUE TITLE
Running by CPU mode, GPU is occupied 

### ISSUE THREAD

**Issue by wangleiofficial** [facebookresearch/esm#20] opened 2021-01-08 14:14 UTC
When running the ESM model CPU mode， i found that GPU was occupied(about 1.7GB)
```
# Load ESM-1b model
model, alphabet = esm.pretrained.esm1b_t33_650M_UR50S()
batch_converter = alphabet.get_batch_converter()

# Prepare data (first 2 sequences from ESMStructuralSplitDataset superfamily / 4)
data = [
    ("protein1", "MKTVRQERLKSIVRILERSKEPVSGAQLAEELSVSRQVIVQDIAYLRSLGYNIVATPRGYVLAGG"),
    ("protein2", "KALTARQQEVFDLIRDHISQTGMPPTRAEIAQRLGFRSPNAAEEHLKALARKGVIEIVSGASRGIRLLQEE"),
]
batch_labels, batch_strs, batch_tokens = batch_converter(data)

# Extract per-residue representations (on CPU)
with torch.no_grad():
    results = model(batch_tokens, repr_layers=[33], return_contacts=True)
token_representations = results["representations"][33]
```

**Comment by joshim5** [comment] 2021-01-08 15:28
HI @wangleiofficial, we can't reproduce this -- we find that the GPU isn't used with this code example. You can [see here](https://github.com/facebookresearch/esm/blob/0ae539bc593ec1ce7def2b384eb91b1eeb34a3c0/esm/pretrained.py#L30) that the model is explicitly loaded to CPU.

Is it possible that you have another process running that is using the GPU?

Closing this out in the meantime since I can't reproduce, but feel free to re-open if you have more information or any more questions.

**Closed by joshim5** 2021-01-08 15:28 UTC

**Comment by wangleiofficial** [comment] 2021-01-11 07:46
hello, i seems that i install [esm verison == 0.10](https://github.com/facebookresearch/esm/blob/v0.1.0/esm/pretrained.py#L42), since the pre-trained model is the CUDA tensor , clearly add map_location 'CPU'?

ESM v0.1.0
```
def load_model_and_alphabet_local(model_location):
    alphabet = esm.Alphabet.from_dict(proteinseq_toks)

    model_data = torch.load(model_location)

    # upgrade state dict
    pra = lambda s: ''.join(s.split('decoder_')[1:] if 'decoder' in s else s)
    prs = lambda s: ''.join(s.split('decoder.')[1:] if 'decoder' in s else s)
    model_args = {pra(arg[0]): arg[1] for arg in vars(model_data["args"]).items()}
    model_state = {prs(arg[0]): arg[1] for arg in model_data["model"].items()}

    model = esm.ProteinBertModel(
        Namespace(**model_args), len(alphabet), padding_idx=alphabet.padding_idx
    )
    model.load_state_dict(model_state)
    return model, alphabet
```

**Comment by joshim5** [comment] 2021-01-11 14:49
That could be the error. Please use v0.2.0 which is the latest supported version.
